### ISSUE TITLE
Can't resolve 'otp-input-react'

### ISSUE THREAD

**Issue by praneetha-ck-robo** [shubhanus/otp-input-react#23]
This issue was noticed when upgrading from version 0.2.0 to 0.2.4.
When I checked the `node_modules` there is no entry file index.js file, in fact there is no js file at all.

Edit: I followed up closely and I have observed this issue started occurring in V-0.2.2 itself. Version 0.2.1 and below has the dist folder and versions 0.2.2 and future versions is missing the dist folder in the node_modules directory @shubhanus

**Comment by niraj-patel** [comment]
Still facing this issue, any update on this?

**Comment by kazmiali** [comment]
I am also facing the same issue

**Comment by kazmiali** [comment]
I just installed it again with version 0.2.0 and it works totally fine.

**Comment by hotdang-ca** [comment]
I'm going to take a look. Turns out `node_modules/otp-input-react` is empty on current version.

**Comment by fleischman718** [comment]
I am also facing the same issue

**Comment by theutkarshsoni** [comment]
I faced the same issue. I tried to delete package-lock.json and node_modules as well but no luck. So give up the idea of using this.

**Comment by theutkarshsoni** [comment]
@kazmiali Thanks for your second comment. The 0.2.0 version working fine. I didn't read that previously.

**Comment by choyan** [comment]
As @kazmiali said, I had to install v0.2.0.
` yarn add otp-input-react@0.2.0`

**Comment by VimLeSai** [comment]
@shubhanus  i think you forget to push build folder into package.

**Comment by mersed** [comment]
> @shubhanus i think you forget to push build folder into package.

Indeed. Same issue here. Switched bak to 0.2.0

**Comment by Parameshvadivel** [comment]
@shubhanus have you pushed the build?

**Comment by justiceotuya** [comment]
its 2021 and this issue still stands

**Comment by Temi-t** [comment]
Same issue as well and Version 0.2.0  seems peer dependent with lower react versions. It doesn't work with react@17.0.2 which is what I'm currently using.

**Comment by VimLeSai** [comment]
I think this repo is not in maintained anymore. I submited PR to fix this issue but no actions at all.

**Comment by shubhanus** [comment]
Fixed apologies guys I'll try to maintain this from now
also any one interested in maintaining please reach out to me.

**Comment by MohammedAnshabtp** [comment]
As per React 18 you may caught dependency error .So i fix by installing **### npm install --force react-otp-input**
