### ISSUE TITLE
 Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by omkar1117** [shubhanus/otp-input-react#28]
17 verbose stack TypeError: Cannot read property 'match' of undefined
17 verbose stack     at tarballToVersion (/usr/local/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:95:20)
17 verbose stack     at inflatableChild (/usr/local/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:121:22)
17 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:63:12
17 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
17 verbose stack     at Object.gotValue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/reduce.js:155:18)
17 verbose stack     at Object.gotAccum (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/reduce.js:144:25)
17 verbose stack     at Object.tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
17 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:517:31)
17 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:574:18)
17 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:619:10)
17 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:699:18)
17 verbose stack     at _drainQueueStep (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
17 verbose stack     at _drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:131:9)
17 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:147:5)
17 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
17 verbose stack     at processImmediate (internal/timers.js:461:21)
18 verbose cwd /home/cluster/ecommerce/pickbazar
19 verbose Linux 5.4.0-52-generic
20 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "otp-input-react"
21 verbose node v12.19.0
22 verbose npm  v6.14.8
23 error Cannot read property 'match' of undefined
24 verbose exit [ 1, true ]

**Comment by shubhanus** [comment]
Can you provide more context on how to reproduce?
BTW we have released new version please check with that
