### ISSUE TITLE
Support for: autocomplete="one-time-code"?

### ISSUE THREAD

**Issue by KasperAndersson** [shubhanus/otp-input-react#59]
Hi, does the lib support `autocomplete="one-time-code"` ?
https://web.dev/sms-otp-form/#autocomplete%22one-time-code%22

**Comment by yosuke1015** [comment]
I also faced ```autocomplete="one-time-code"``` issue.
@KasperAndersson did you solve this issue?

**Comment by KasperAndersson** [comment]
> I also faced `autocomplete="one-time-code"` issue. @KasperAndersson did you solve this issue?

No, haven't used this lib. I went with native input..
