### ISSUE TITLE
Unmount error in ResendOTP component

### ISSUE THREAD

**Issue by mjf-chi** [shubhanus/otp-input-react#8]
https://github.com/shubhanus/otp-input-react/blob/645022f2ff17b198cf2dded56a09620dffad7320/src/lib/hooks/resendOTP.js#L25

Does this need to be clearTimeout(timeout.current)?

I believe this is causing the following error when the component is unmounted.

`Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.

**Comment by shubhanus** [comment]
Thanks for raising bug @mjf-chi.
